name: Update README

on:
  push:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  readme-scribe:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: templates/README.md.tpl
          writeTo: README.md

      - uses: stefanzweifel/git-auto-commit-action@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: main
          commit_message: Update GitHub activity in README
          commit_author: GitHub Actions <actions@github.com>
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
